# Generated by Django 4.2.2 on 2023-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_category',
            field=models.CharField(blank=True, choices=[('DW', 'Drinking Water'), ('EC', 'Electricity')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SUPERADMIN'), (2, 'ADMIN'), (3, 'USER')], default=3),
        ),
    ]
