# Generated by Django 4.2.2 on 2023-10-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin_category',
            field=models.CharField(blank=True, choices=[('drinking-water', 'Drinking Water'), ('electriciry', 'Electricity'), ('telecommunication', 'Telecommunication')], max_length=255, null=True),
        ),
    ]
