# Generated by Django 4.2.2 on 2023-10-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('complain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('complain_title', models.CharField(max_length=255)),
                ('complain_message', models.TextField()),
                ('complain_image', models.ImageField(null=True, upload_to='Images')),
                ('to_complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.complainname')),
            ],
        ),
    ]
