# Generated by Django 4.2.2 on 2023-10-06 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_complain_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='complain',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_complains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_body', models.TextField(max_length=10000)),
                ('response_image', models.ImageField(null=True, upload_to='Images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('response_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='main.complain')),
            ],
        ),
    ]
