# Generated by Django 4.2.2 on 2023-08-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_complain_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='complain_titile',
            new_name='complain_title',
        ),
    ]
