# Generated by Django 4.2.5 on 2023-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_complain_titile_complain_complain_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('complain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='complain',
            name='to_complain',
        ),
        migrations.AddField(
            model_name='complain',
            name='to_complain',
            field=models.ManyToManyField(blank=True, to='main.complainname'),
        ),
    ]
