# Generated by Django 4.2.5 on 2023-10-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complainname_alter_complain_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='to_complain',
        ),
        migrations.AddField(
            model_name='complain',
            name='to_complain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.complainname'),
            preserve_default=False,
        ),
    ]
